### ISSUE TITLE
Abstract/Intro Q

### ISSUE THREAD

**Issue by jlivingood** [jariarkko/draft-arkko-iasa20-trust#5]
(After reviewing my pull request)

Abstract and Introduction use nearly the exact same text. Perhaps consider reducing the length of the abstract to something such as:

<t>The IASA 2.0 changes will have an impact on the IETF Trust 
      because members of the IET Administrative Oversight
      Committee (IAOC) IAOC, which is being phased out, have served 
      as Trustees of the IETF Trust. This discussion document provides 
      background on the current IETF Trust arrangements, explains the effect of
      the rules in the founding documents during a transition to a new
      arrangement, and provides a rationale for the update.</t>

**Comment by jariarkko** [comment]
Yeah, probably good. Will implement.
